### ISSUE TITLE
@types included in dependencies

### ISSUE THREAD

**Issue by niksoper** [googleapis/nodejs-common#392]
#### Environment details

  - OS: Mac Mojave
  - Node.js version: `8.9.1` | `8.15.0` | `10.14.0`
  - npm version: `5.5.1` | `6.4.1`
  - `@google-cloud/common` version: `0.31.1`

#### Steps to reproduce

  1. Create empty npm package:`npm init`
  2. Add @google-cloud/common as a dependency: `yarn add @google-cloud/common@0.31.1`

We now have this `package.json`:
```
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/common": "0.31.1"
  }
}
```

  4. List all TypeScript typings from dependencies: `ls node_modules/@types`:
```
caseless     duplexify    form-data    node         request      tough-cookie
```

  3. Check why we have these:
```
yarn why @types/request

yarn why v1.13.0
[1/4] 🤔  Why do we have the module "@types/request"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/request@2.48.1"
info Reasons this module exists
   - "@google-cloud#common" depends on it
   - Hoisted from "@google-cloud#common#@types#request"
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "796KB"
info Disk size with transitive dependencies: "796KB"
info Number of shared dependencies: 4
✨  Done in 0.11s.
```
```
yarn why @types/duplexify

yarn why v1.13.0
[1/4] 🤔  Why do we have the module "@types/duplexify"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/duplexify@3.6.0"
info Reasons this module exists
   - "@google-cloud#common" depends on it
   - Hoisted from "@google-cloud#common#@types#duplexify"
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "732KB"
info Disk size with transitive dependencies: "732KB"
info Number of shared dependencies: 1
✨  Done in 0.11s.
```

This adds 100's of KB of dependencies which could be avoided ifthe `@types` were in `devDependencies` instead of `dependencies`.

This is significant if you're using Cloud Functions because it will impact cold start times.

**Comment by JustinBeckwith** [comment]
Yeah....  that's sadly by (bad) design at this stage.  This library exports interfaces that include `Duplexify` streams.  As a result, it causes TypeScript compilation errors for downstream users if we *don't* include that in the non-dev-dependencies.  

I honestly don't know the right answer here.  @ofrobots loves this topic :)

**Comment by ofrobots** [comment]
I've written about the root cause previous here: https://github.com/googleapis/nodejs-logging-bunyan/issues/243.

This is a problem with TypeScript and npm. Dependency types can [leak](https://speakerdeck.com/southpolesteve/shipping-typescript-to-npm?slide=45) to users of a TypeScript module. The problem is that it is not possible to express type-dependencies as neither `dependencies` nor `devDependency` express the desired semantics. The two generally used workarounds (also mentioned in this [deck](https://speakerdeck.com/southpolesteve/shipping-typescript-to-npm?slide=45)) are:

1. Add a type dependency to a `@types` package. I personally dislike this because it shifts the burden to the users of module (even if they don't use TypeScript). This is the complaint from @niksoper.
1. Mirror (i.e. copy) the dependent types. This seems ugly and is work for developers of the module who have to keep their copy up to date with upstream. I argue that this is less evil.

It would nice the TypeScript ecosystem could come up with more scalable solutions.

**Comment by niksoper** [comment]
I had a feeling this would not be a straightforward oversight! 😃 

Thanks for the quick replies though.
